# Generated by Django 6.0.8 on 2026-10-05 22:20

import django.db.models.deletion
from django.db import migrations, models

import world.loot_entities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_entities', '0003_magazine_socket'),
        ('objects', '0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_until', models.FloatField(default=0, validators=[world.loot_entities.models.validate_time])),
                ('quantity', models.PositiveBigIntegerField()),
                ('owner_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_loot', to='objects.objectdb')),
                ('reserved_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('reserved_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyLootShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount', models.PositiveBigIntegerField()),
                ('currency_loot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='loot_entities.currencyloot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='LootClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_until', models.FloatField(default=0, validators=[world.loot_entities.models.validate_time])),
                ('assigned_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='objects.objectdb')),
                ('item_entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loot_claim', to='item_entities.itementity')),
                ('reserved_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('reserved_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='objects.objectdb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='currencyloot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='currency_loot_positive'),
        ),
        migrations.AddConstraint(
            model_name='currencylootshare',
            constraint=models.UniqueConstraint(fields=('currency_loot', 'player'), name='currency_share_player_unique'),
        ),
        migrations.AddConstraint(
            model_name='currencylootshare',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='currency_share_nonnegative'),
        ),
    ]
