"""명령 등록 목록. 자동 discovery 없이 여기에서 조합한다."""

from commands.base import UnknownCommand
from commands.character import (
    Abilities,
    Experience,
    GlobalShortcuts,
    Help,
    Look,
    Map,
    Quest,
    Skills,
    Status,
    Weather,
)
from commands.combat import Attack, Breathe, Flee, Heal, Heavy, Insight, Shooting, Suppress, Use
from commands.command_shortcuts import Sequence, Shortcuts
from commands.firearms import FillMagazine, LoadMagazine, Reload
from commands.inventory import (
    ActiveWeapon,
    Buy,
    Equip,
    Equipment,
    Inventory,
    Sell,
    Shop,
    Take,
    Value,
    Wield,
)
from commands.items import (
    Drink,
    Drop,
    Eat,
    Give,
    LightOff,
    LightOn,
    LightStatus,
    RemoveArmor,
    Retrieve,
    Store,
    Unwield,
)
from commands.party import (
    PartyAccept,
    PartyCommand,
    PartyInvite,
    PartyKick,
    PartyLeave,
    PartyLootMode,
    PartyReject,
    PartyTransfer,
)
from commands.settlement import Exchange, Rate
from commands.skills import Allocate, Learn, Retrain
from commands.social import Say
from commands.world_actions import Investigate, Repair, Rest, Return, Talk, Treat

COMMANDS = [
    Reload,
    LoadMagazine,
    FillMagazine,
    Abilities,
    Skills,
    Experience,
    Equipment,
    ActiveWeapon,
    Learn,
    Allocate,
    Retrain,
    Take,
    PartyLootMode,
    PartyCommand,
    PartyInvite,
    PartyAccept,
    PartyReject,
    PartyLeave,
    PartyKick,
    PartyTransfer,
    Look,
    Weather,
    Help,
    GlobalShortcuts,
    Sequence,
    Shortcuts,
    Status,
    Inventory,
    Wield,
    Equip,
    Drop,
    Give,
    Eat,
    Drink,
    RemoveArmor,
    Unwield,
    Store,
    Retrieve,
    LightOn,
    LightOff,
    LightStatus,
    Attack,
    Heavy,
    Shooting,
    Insight,
    Suppress,
    Heal,
    Breathe,
    Use,
    Flee,
    Return,
    Rest,
    Treat,
    Shop,
    Buy,
    Value,
    Sell,
    Exchange,
    Rate,
    Quest,
    Talk,
    Investigate,
    Repair,
    Map,
    Say,
    UnknownCommand,
]
