"""두 번째 탐사 지역: 깊은 밀림."""

ENEMIES = {
    "dartclaw": {
        "training_cap": 7,
        "name": "날쌘발톱룡",
        "description": "낮은 관목 사이를 빠르게 오가며 틈을 노리는 포식자다.",
        "combat_mode": "claimed",
        "hp": 52,
        "attack": 15,
        "defense": 1,
        "xp": 55,
        "credits": 18,
        "drop": "bandage",
        "chance": 0.25,
    },
    "shellback": {
        "training_cap": 8,
        "name": "철갑등짐승",
        "description": "등을 덮은 두꺼운 껍질 때문에 묵직한 일격이 필요하다.",
        "combat_mode": "claimed",
        "hp": 92,
        "attack": 12,
        "defense": 6,
        "xp": 70,
        "credits": 24,
        "drop": "scrap",
        "chance": 0.2,
    },
    "stalker": {
        "training_cap": 9,
        "name": "그늘추적룡",
        "description": "거목 그림자 속에서 오래 먹잇감을 쫓는 사냥룡이다.",
        "combat_mode": "claimed",
        "hp": 104,
        "attack": 18,
        "defense": 3,
        "xp": 84,
        "credits": 29,
        "drop": "bandage",
        "chance": 0.3,
    },
    "jungle_apex": {
        "training_cap": 10,
        "name": "밀림의포식자",
        "description": "깊은 숲을 지배하는 거대한 포식자다. 몸을 뒤틀어 도약하기 전에 숨을 고른다.",
        "combat_mode": "public",
        "hp": 190,
        "attack": 20,
        "defense": 4,
        "xp": 155,
        "credits": 58,
        "drop": "apex_scale",
        "chance": 1.0,
        "boss": True,
        "boss_quest": "deep_jungle",
        "special_period": 4,
        "special_verb": "몸을 날려 덮쳐",
        "telegraph": "숨을 고르며 도약할 자세를 취한다.",
    },
}

ROOMS = {
    "jungle_edge": {
        "name": "밀림 입구",
        "enemies": ["dartclaw"],
        "desc": "통신탑 뒤편 길이 빽빽한 밀림으로 이어진다. 선발대가 남긴 발자국이 젖은 흙 위에 남아 있다.",
        "hint": "선발대 길잡이 대화",
        "exits": {"남": "ridge", "북": "jungle_watch", "동": "jungle_road", "서": "jungle_fen"},
        "requires": {
            "quest": "radio_tower",
            "flag": "claimed",
            "message": "먼저 통신탑 복구 임무를 마치고 윤대장에게 보고하세요.",
        },
    },
    "jungle_watch": {
        "name": "버려진 관측소",
        "enemies": ["dartclaw"],
        "desc": "나무 위 관측소가 덩굴에 묻혀 있다. 오래된 탐사 표식이 입구에 남아 있다.",
        "hint": "관측 표식 조사",
        "exits": {"남": "jungle_edge", "동": "jungle_grove"},
    },
    "jungle_road": {
        "name": "수몰된 도로",
        "enemies": ["shellback"],
        "desc": "물에 잠긴 옛 도로 사이로 단단한 껍질의 짐승이 천천히 움직인다.",
        "hint": "수위 표식 조사",
        "exits": {"서": "jungle_edge", "북": "jungle_grove"},
    },
    "jungle_fen": {
        "name": "늪지 샛길",
        "enemies": ["stalker"],
        "desc": "검은 물 위로 좁은 길이 갈라진다. 버려진 보급 주머니가 반쯤 잠겨 있다.",
        "hint": "늪지 보급품 조사",
        "exits": {"동": "jungle_edge"},
    },
    "jungle_grove": {
        "name": "거목 군락",
        "enemies": ["shellback", "stalker"],
        "desc": "거목 뿌리 사이에서 관측소와 도로의 흔적이 만난다. 닫힌 출입문 옆에 신호 장치가 놓였다.",
        "hint": "신호 장치 조사",
        "exits": {"서": "jungle_watch", "남": "jungle_road", "북": "jungle_gate"},
    },
    "jungle_gate": {
        "name": "연구구역 외곽",
        "enemies": ["stalker"],
        "desc": "선발대의 신호가 낡은 문을 열었다. 안쪽 깊은 둥지에서 커다란 그림자가 움직인다.",
        "hint": "둥지로 들어가기 전 장비와 붕대를 확인하자.",
        "exits": {"남": "jungle_grove", "북": "jungle_nest"},
        "requires": {
            "quest": "deep_jungle",
            "flag": "gate_open",
            "message": "연구구역 문이 닫혀 있습니다. 두 탐사 표식을 확인하고 거목의 신호 장치를 조사하세요.",
        },
    },
    "jungle_nest": {
        "name": "포식자 둥지",
        "enemies": ["jungle_apex"],
        "desc": "휘어진 나무 아래에 거대한 둥지가 있다. 바닥에는 오래된 탐사대 장비가 흩어져 있다.",
        "hint": "포식자가 숨을 고르면 방어 자세를 취하자.",
        "exits": {"남": "jungle_gate"},
    },
}
