"""본부 5층·옥상 콘텐츠. 폐지 ID는 영속 객체 보존용 전환표로 유지한다."""

ROOF_SIDES = {
    "북": "support_roof_n",
    "북동": "support_roof_ne",
    "동": "support_roof_e",
    "남동": "support_roof_se",
    "남": "support_roof_s",
    "남서": "support_roof_sw",
    "서": "support_roof_w",
    "북서": "support_roof_nw",
}
ROOF_ROOMS = {"support_roof", *ROOF_SIDES.values()}

RETIRED_ROOMS = {
    "support_1f_w2": "hq_concourse",
    "support_1f_w1": "hq_concourse",
    "support_1f_c": "hq_concourse",
    "support_1f_e1": "hq_concourse",
    "support_1f_e2": "hq_concourse",
    "support_2f_w2": "support_2f_w1",
    "support_2f_e2": "support_2f_e1",
    "support_3f_w2": "support_3f_w1",
    "support_3f_e2": "support_3f_e1",
}

ROOMS = {
    "staging_room": {
        "name": "출정 대기실",
        "desc": "출정을 기다리는 탐사자들을 위한 대기실이다. 벽을 따라 낡은 의자와 보급 상자가 놓여 있다.\n남쪽 문 너머로 본부의 분주한 소리가 들려온다.",
        "exits": {"남": "hq_concourse"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "hq_concourse": {
        "name": "본부 중앙 로비",
        "desc": "높은 천장 아래로 본부의 넓은 로비가 펼쳐진다. 북쪽은 출정 대기실, 서쪽은 부두로 이어진다. 동쪽에는 관리실, 남쪽에는 휴게실이 있다. 중앙의 "
        "계단과 승강기로 각 층에 오갈 수 있다.",
        "exits": {"북": "staging_room", "서": "dock", "동": "hq_admin_office", "남": "hq_lounge"},
        "recovery": {"hp_per_minute": 2, "mental_per_minute": 2},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "hq_admin_office": {
        "name": "본부 관리실",
        "desc": "본부의 안내 문서와 시설 배치도가 책상 위에 정리되어 있다. 서쪽 문은 중앙 로비로 이어진다.",
        "exits": {"서": "hq_concourse"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "hq_lounge": {
        "name": "본부 휴게실",
        "desc": "낡은 소파와 의자가 탐사자를 기다린다. 북쪽 문 너머로 중앙 로비의 분주한 소리가 들린다.",
        "exits": {"북": "hq_concourse"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_2f_w1": {
        "name": "본부 2층 서쪽 복도",
        "desc": "본부 2층 서쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 보관실 표지가 붙어 있다.",
        "exits": {"동": "support_2f_c", "북": "storage_room"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_2f_c": {
        "name": "본부 2층 중앙 복도",
        "desc": "본부 2층 중앙 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 중앙에 계단과 승강기가 있다. 북쪽 문에는 보급품 상점 표지가 붙어 있다.",
        "exits": {"서": "support_2f_w1", "동": "support_2f_e1", "북": "supply_shop"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_2f_e1": {
        "name": "본부 2층 동쪽 복도",
        "desc": "본부 2층 동쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 자원 정산소 표지가 붙어 있다.",
        "exits": {"서": "support_2f_c", "북": "salvage_office"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_3f_w1": {
        "name": "본부 3층 서쪽 복도",
        "desc": "본부 3층 서쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 의료 대기실 표지가 붙어 있다.",
        "exits": {"동": "support_3f_c", "북": "medical_waiting"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_3f_c": {
        "name": "본부 3층 중앙 복도",
        "desc": "본부 3층 중앙 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 중앙에 계단과 승강기가 있다. 북쪽 문에는 의무실 표지가 붙어 있다.",
        "exits": {"서": "support_3f_w1", "동": "support_3f_e1", "북": "infirmary"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_3f_e1": {
        "name": "본부 3층 동쪽 복도",
        "desc": "본부 3층 동쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 회복실 표지가 붙어 있다.",
        "exits": {"서": "support_3f_c", "북": "recovery_room"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_4f_w1": {
        "name": "본부 4층 서쪽 복도",
        "desc": "본부 4층 서쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 전투훈련실 표지가 붙어 있다. 남쪽 문에는 생존훈련실 표지가 붙어 "
        "있다.",
        "exits": {"동": "support_4f_c", "북": "training_room", "남": "survival_training_room"},
        "blocked_exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_4f_c": {
        "name": "본부 4층 중앙 복도",
        "desc": "본부 4층 중앙 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 중앙에 계단과 승강기가 있다. 북쪽 문에는 훈련관리실 표지가 붙어 있다. 남쪽 "
        "문에는 전술훈련실 표지가 붙어 있다.",
        "exits": {
            "서": "support_4f_w1",
            "동": "support_4f_e1",
            "북": "training_office",
            "남": "tactics_room",
        },
        "blocked_exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_4f_e1": {
        "name": "본부 4층 동쪽 복도",
        "desc": "본부 4층 동쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 사격장 표지가 붙어 있다. 남쪽 문에는 의료훈련실 표지가 붙어 "
        "있다.",
        "exits": {"서": "support_4f_c", "북": "shooting_range", "남": "medical_training_room"},
        "blocked_exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_5f_w2": {
        "name": "본부 5층 서쪽 끝 복도",
        "desc": "본부 5층 서쪽 끝 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 전초 장비고 표지가 붙어 있다. 남쪽 문에는 다음 단계 장비고 "
        "표지가 붙어 있다.",
        "exits": {"동": "support_5f_w1", "북": "outpost_equipment", "남": "reserved_equipment"},
        "blocked_exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_5f_w1": {
        "name": "본부 5층 서쪽 복도",
        "desc": "본부 5층 서쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 기본 장비점 표지가 붙어 있다.",
        "exits": {"서": "support_5f_w2", "동": "support_5f_c", "북": "armor_shop"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_5f_c": {
        "name": "본부 5층 중앙 복도",
        "desc": "본부 5층 중앙 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 중앙에 계단과 승강기가 있다.",
        "exits": {"서": "support_5f_w1", "동": "support_5f_e1"},
        "blocked_exits": {
            "북": "북쪽 출입문은 현재 폐쇄되어 있다.",
            "남": "남쪽 출입문은 현재 폐쇄되어 있다.",
        },
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_5f_e1": {
        "name": "본부 5층 동쪽 복도",
        "desc": "본부 5층 동쪽 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 기본 병기점 표지가 붙어 있다.",
        "exits": {"서": "support_5f_c", "동": "support_5f_e2", "북": "weapon_shop"},
        "blocked_exits": {"남": "남쪽 출입문은 현재 폐쇄되어 있다."},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_5f_e2": {
        "name": "본부 5층 동쪽 끝 복도",
        "desc": "본부 5층 동쪽 끝 복도다. 벽의 안내판이 이 층의 시설을 가리킨다. 북쪽 문에는 전초 병기고 표지가 붙어 있다. 남쪽 문에는 다음 단계 병기고 "
        "표지가 붙어 있다.",
        "exits": {"서": "support_5f_e1", "북": "outpost_weapon", "남": "reserved_weapon"},
        "blocked_exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "storage_room": {
        "name": "보관실",
        "desc": "두꺼운 벽으로 둘러싸인 보관 공간이다. 벽을 따라 빈 선반이 줄지어 있고 남쪽 문은 본부 2층 복도로 이어진다.",
        "exits": {"남": "support_2f_w1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "supply_shop": {
        "name": "보급품 상점",
        "desc": "낮은 진열대와 비어 있는 판매대가 놓인 공간이다. 남쪽 문은 본부 2층 복도로 이어진다.",
        "exits": {"남": "support_2f_c"},
        "hints": [{"target": "supply_shopkeeper", "action": "목록"}],
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "salvage_office": {
        "name": "자원 정산소",
        "desc": "넓은 작업대와 비어 있는 금속 선반이 놓인 업무 공간이다. 남쪽 문은 본부 2층 복도로 이어진다.",
        "exits": {"남": "support_2f_e1"},
        "hints": [{"target": "salvage_officer", "action": "환율"}],
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "medical_waiting": {
        "name": "의료 대기실",
        "desc": "의무실을 기다리는 탐사자들을 위한 의자가 벽을 따라 놓여 있다. 남쪽 문은 본부 3층 복도로 이어진다.",
        "exits": {"남": "support_3f_w1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "infirmary": {
        "name": "의무실",
        "desc": "밝은 타일로 마감된 넓은 공간이다. 벽의 수납장은 비어 있고 남쪽 문은 본부 3층 복도로 이어진다.",
        "exits": {"남": "support_3f_c"},
        "hints": [
            {"target": "doctor", "action": "진료"},
            {"target": "infirmary_bed", "action": "휴식"},
        ],
        "recovery": {"hp_per_minute": 6, "mental_per_minute": 2},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "recovery_room": {
        "name": "회복실",
        "desc": "조용한 방 안에 회복을 기다리는 탐사자들을 위한 자리가 마련되어 있다. 남쪽 문은 본부 3층 복도로 이어진다.",
        "exits": {"남": "support_3f_e1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "training_room": {
        "name": "전투훈련실",
        "desc": "단단한 바닥의 대련 구획 옆으로 무기 연습대와 중량 훈련 장비가 놓여 있다. 남쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"남": "support_4f_w1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "survival_training_room": {
        "name": "생존훈련실",
        "desc": "벽을 따라 방호 장비와 체력 단련 기구가 놓여 있다. 바닥 매트를 깐 한쪽 구획은 호흡 훈련 공간이다. 북쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"북": "support_4f_w1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "training_office": {
        "name": "훈련관리실",
        "desc": "훈련 기록을 보관하는 수납장 앞에 상담용 책상과 의자가 놓여 있다. 벽의 안내판에는 재훈련 절차가 적혀 있다. 남쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"남": "support_4f_c"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "tactics_room": {
        "name": "전술훈련실",
        "desc": "작전 지도와 지형 모형이 낮은 탁자 위에 놓여 있다. 벽의 분석판에는 전투 상황과 이동 경로를 표시할 수 있는 격자가 그려져 있다. 북쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"북": "support_4f_c"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "shooting_range": {
        "name": "사격장",
        "desc": "두꺼운 방음벽 안쪽에 사격선과 이동 표적용 레일이 놓여 있다. 표적 뒤는 모래 둔덕으로 막혀 있고 옆 구획에는 기동 훈련용 장애물이 배치되어 있다. 남쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"남": "support_4f_e1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "medical_training_room": {
        "name": "의료훈련실",
        "desc": "실습대 위에 처치 모형과 응급 실습 장비가 정돈되어 있다. 벽의 선반에는 연습용 붕대와 고정구가 놓여 있다. 북쪽 문은 본부 4층 복도로 이어진다.",
        "exits": {"북": "support_4f_e1"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "armor_shop": {
        "name": "기본 장비점",
        "desc": "빈 진열대가 벽을 따라 놓여 있다. 남쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"남": "support_5f_w1"},
        "hints": [{"target": "armor_shopkeeper", "action": "목록"}],
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "weapon_shop": {
        "name": "기본 병기점",
        "desc": "튼튼한 판매대와 비어 있는 장비 걸이가 놓인 공간이다. 남쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"남": "support_5f_e1"},
        "hints": [{"target": "weapon_shopkeeper", "action": "목록"}],
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "outpost_equipment": {
        "name": "전초 장비고",
        "desc": "전초 장비고의 출입문 너머로 장비 보급 시설이 보인다. 남쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"남": "support_5f_w2"},
        "hints": [{"target": "outpost_equipment_shopkeeper", "action": "목록"}],
        "access": {"available": True, "credential": "outpost_supply_pass"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "outpost_weapon": {
        "name": "전초 병기고",
        "desc": "전초 병기고의 출입문 너머로 장비 보급 시설이 보인다. 남쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"남": "support_5f_e2"},
        "hints": [{"target": "outpost_weapon_shopkeeper", "action": "목록"}],
        "access": {"available": True, "credential": "outpost_supply_pass"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "reserved_equipment": {
        "name": "다음 단계 장비고",
        "desc": "다음 단계 장비고의 출입문 너머로 장비 보급 시설이 보인다. 북쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"북": "support_5f_w2"},
        "access": {"available": False, "credential": "special_supply_pass"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "reserved_weapon": {
        "name": "다음 단계 병기고",
        "desc": "다음 단계 병기고의 출입문 너머로 장비 보급 시설이 보인다. 북쪽 문은 본부 5층 복도로 이어진다.",
        "exits": {"북": "support_5f_e2"},
        "access": {"available": False, "credential": "special_supply_pass"},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
    "support_roof": {
        "name": "본부 옥상",
        "desc": "콘크리트 난간이 본부의 옥상을 둘러싸고 있다. 낡은 바닥 너머로 본부의 지붕과 섬의 숲이 보인다.",
        "exits": {
            "북": "support_roof_n",
            "북동": "support_roof_ne",
            "동": "support_roof_e",
            "남동": "support_roof_se",
            "남": "support_roof_s",
            "남서": "support_roof_sw",
            "서": "support_roof_w",
            "북서": "support_roof_nw",
        },
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_n": {
        "name": "북쪽 전망 구역",
        "desc": "난간 너머로 본부 진입로가 내려다보인다. 바닥의 마모된 선을 따라 옥상 중앙으로 돌아갈 수 있다.",
        "exits": {"남": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_ne": {
        "name": "북동쪽 설비 구역",
        "desc": "낡은 설비 덮개가 콘크리트 받침 위에 놓여 있다. 배관 사이로 옥상 중앙이 보인다.",
        "exits": {"남서": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_e": {
        "name": "동쪽 난간",
        "desc": "높은 난간 너머로 숲의 가장자리가 펼쳐진다. 탁 트인 바닥이 옥상 중앙으로 이어진다.",
        "exits": {"서": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_se": {
        "name": "남동쪽 급수 설비",
        "desc": "두꺼운 급수관이 물탱크 아래로 이어진다. 설비 옆의 넓은 공간을 통해 중앙으로 돌아갈 수 있다.",
        "exits": {"북서": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_s": {
        "name": "남쪽 전망 구역",
        "desc": "섬의 남쪽 수평선이 본부 지붕 너머로 보인다. 옥상 중앙까지 평평한 바닥이 이어진다.",
        "exits": {"북": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_sw": {
        "name": "남서쪽 환기 구역",
        "desc": "금속 환기구가 낮은 받침 위에 줄지어 있다. 그 사이로 중앙에 이르는 빈 공간이 남아 있다.",
        "exits": {"북동": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_w": {
        "name": "서쪽 난간",
        "desc": "난간 아래로 부두의 윤곽이 보인다. 낡은 바닥을 따라 옥상 중앙으로 돌아갈 수 있다.",
        "exits": {"동": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_roof_nw": {
        "name": "북서쪽 통신 설비",
        "desc": "짧은 안테나와 밀폐된 통신함이 놓여 있다. 케이블 덮개 옆으로 중앙에 이르는 공간이 열려 있다.",
        "exits": {"남동": "support_roof"},
        "safe": True,
        "enemies": [],
        "exposure": "outdoor",
        "light_profile": "natural",
        "recovery": {"mental_per_minute": 2},
    },
    "support_elevator": {
        "name": "본부 승강기",
        "desc": "금속 벽으로 둘러싸인 공용 승강기다. 조작반에는 1층, 2층, 3층, 4층, 5층, 옥상 버튼이 있다.",
        "exits": {},
        "safe": True,
        "enemies": [],
        "exposure": "indoor",
        "light_profile": "artificial",
    },
}


# 구조 정의에만 사용하는 순서. 런타임 이동·표시는 아래 실제 Exit를 읽는다.
HQ_LANDINGS = (
    ("1층", "hq_concourse", "hq_stairs_1f"),
    ("2층", "support_2f_c", "hq_stairs_2f"),
    ("3층", "support_3f_c", "hq_stairs_3f"),
    ("4층", "support_4f_c", "hq_stairs_4f"),
    ("5층", "support_5f_c", "hq_stairs_5f"),
    ("옥상", "support_roof", "hq_stairs_roof"),
)
ELEVATOR_ROOM = "support_elevator"
ROOMS[ELEVATOR_ROOM]["exits"] = {label: landing for label, landing, _ in HQ_LANDINGS}
for index, (label, landing, stairs) in enumerate(HQ_LANDINGS):
    exits = {}
    if index + 1 < len(HQ_LANDINGS):
        exits["위"] = HQ_LANDINGS[index + 1][2]
    if index:
        exits["아래"] = HQ_LANDINGS[index - 1][2]
    exits["나가기"] = landing
    ROOMS[stairs] = {
        "name": f"본부 {label} 계단",
        "desc": (f"본부 {label}의 계단참이다. 콘크리트 계단 가장자리에 금속 난간이 이어지고 "
                 f"층 표지가 벽에 붙어 있다. 문 너머는 {ROOMS[landing]['name']}이다."),
        "exits": exits, "safe": True, "enemies": [],
        "exposure": "indoor", "light_profile": "artificial",
    }
    ROOMS[landing]["exits"].update({"계단": stairs, "승강기": ELEVATOR_ROOM})
