"""탐사대 전초구역의 기존 stable Room/Enemy 정의."""

ENEMIES = {
    "scavenger": {
        "training_cap": 2,
        "name": "어린청소룡",
        "description": "작은 몸집의 육식 공룡이다. 날카로운 이빨을 드러내며 주변을 경계한다.",
        "combat_mode": "claimed",
        "hp": 24,
        "attack": 5,
        "defense": 0,
        "xp": 22,
        "credits": 8,
        "drop": "blade",
        "chance": 0.25,
    },
    "hunter": {
        "training_cap": 4,
        "name": "갈퀴사냥룡",
        "description": "굽은 발톱을 가진 사냥룡이다. 낮게 엎드린 자세로 먹잇감의 움직임을 살핀다.",
        "combat_mode": "claimed",
        "hp": 42,
        "attack": 9,
        "defense": 1,
        "xp": 38,
        "credits": 14,
        "drop": "armor",
        "chance": 0.25,
    },
    "sentinel": {
        "training_cap": 7,
        "name": "고장난경비기",
        "description": "외장이 부서진 경비 기계다. 감지기가 움직일 때마다 금속 마찰음이 들린다.",
        "combat_mode": "claimed",
        "hp": 60,
        "attack": 11,
        "defense": 3,
        "xp": 55,
        "credits": 20,
        "drop": "carbine",
        "chance": 0.15,
    },
    "alpha": {
        "training_cap": 10,
        "name": "능선의우두머리",
        "description": "능선을 차지한 거대한 포식자다. 돌진하기 전 몸을 낮추는 습성이 있다.",
        "combat_mode": "public",
        "hp": 130,
        "attack": 17,
        "defense": 3,
        "xp": 130,
        "credits": 50,
        "drop": "fang",
        "chance": 1.0,
        "boss": True,
        "boss_quest": "radio_tower",
        "special_period": 3,
    },
}

ROOMS = {
    "dock": {
        "name": "탐사대 부두",
        "safe": True,
        "enemies": [],
        "desc": "안개 너머로 버려진 섬이 드러난다. 낡은 선착장에 밧줄과 장비가 가지런히 놓여 있다.\n"
        "정박한 배 사이로 잔물결이 일고, 먼 숲에서 새소리가 들려온다.",
        "hint": "윤대장 대화 · 상점 · 휴식",
        "exits": {"북": "grass"},
    },
    "grass": {
        "name": "바람 부는 초지",
        "enemies": ["scavenger"],
        "desc": "무릎 높이의 풀 사이로 작은 발자국이 이어진다. 첫 사냥에 적당한 곳이다.",
        "hint": "어린청소룡 공격 · 강타 · 상태",
        "exits": {"남": "dock", "동": "wreck", "북": "trail"},
    },
    "wreck": {
        "name": "부서진 수송차",
        "enemies": ["scavenger"],
        "desc": "수송차가 옆으로 뒤집힌 채 풀숲에 박혀 있다. 누군가 남긴 물자를 찾을 수 있을 것 같다.",
        "hint": "보급상자 조사",
        "exits": {"서": "grass"},
    },
    "trail": {
        "name": "발톱 자국 오솔길",
        "enemies": ["hunter"],
        "desc": "나무마다 깊은 발톱 자국이 남아 있다. 초지보다 강한 사냥룡이 이곳을 배회한다.",
        "hint": "장비를 바꾸고 체력을 확인하자.",
        "exits": {"남": "grass", "동": "office", "북": "marsh"},
    },
    "office": {
        "name": "폐쇄된 관리동",
        "enemies": [],
        "desc": "비가 새는 천장 아래로 젖은 책상이 보인다. 바람이 들어올 때마다 종잇장이 들썩인다.",
        "hint": "정비기록 조사",
        "exits": {"서": "trail", "동": "generator"},
    },
    "generator": {
        "name": "멈춰 선 발전실",
        "enemies": ["sentinel"],
        "desc": "기름 냄새가 밴 발전실에 녹슨 배관이 얽혀 있다. 바닥에는 오래된 기름 자국이 남아 있다.",
        "hint": "발전기 수리",
        "exits": {"서": "office"},
    },
    "marsh": {
        "name": "물안개 습지",
        "enemies": ["hunter", "sentinel"],
        "desc": "진흙 위로 생물의 흔적과 기계의 궤적이 교차한다. 북쪽 능선에서 낮은 울음소리가 들린다.",
        "hint": "능선 진입 전 강화조끼와 붕대를 준비하자.",
        "exits": {"남": "trail", "북": "ridge"},
    },
    "ridge": {
        "name": "통신탑 능선",
        "enemies": ["alpha"],
        "desc": "통신탑을 둘러싼 덩굴 사이로 거대한 그림자가 움직인다. 전력이 복구되어야 접근할 수 있다.",
        "hint": "우두머리가 몸을 낮추면 다음 공격을 방어하자.",
        "exits": {"남": "marsh", "북": "jungle_edge"},
        "requires": {"quest": "radio_tower", "flag": "generator_fixed", "message": "통신탑 진입문이 잠겨 있습니다. 정비기록을 읽고 발전기를 수리하세요."},
    },
}
